### ISSUE TITLE
proper handling of "git commit --amend"

### ISSUE THREAD

**Issue by steinymity** [rhysd/committia.vim#36] opened 2017-07-19 10:29 UTC
When calling "git commit --amend" the commit message window stays empty and does not show the former commit message for editing. Moreover, there is no way to abort the commit-amend, so the history is rewritten in any case.
Thanks for the great plugin and for working on this minor issue!
Best,
Maximilian

**Comment by rhysd** [comment] 2017-07-20 13:29
Yeah I noticed this. I marked this as bug and will try to fix this when I have a time

**Comment by steinymity** [comment] 2017-07-23 14:48
I just noticed that the same happens for merges — the automatic text does not show up.

**Comment by steinymity** [comment] 2017-08-16 14:46
Interestingly, for git commit --amend the original commit message is only missing in the large view, not in the one-column view.

**Comment by rhysd** [comment] 2018-01-28 09:24
Closing this because of #38.

**Closed by rhysd** 2018-01-28 09:24 UTC
Labels: bug

**Comment by kinbiko** [comment] 2022-09-24 15:26
@rhysd I don't understand how #38 addressed this issue, and `--amend` still doesn't show the diff. Is that intended behaviour now? Thank you 🙇
