### ISSUE TITLE
Does not work with filetype.nvim

### ISSUE THREAD

**Issue by tsakirist** [rhysd/committia.vim#56] opened 2021-11-07 12:57 UTC
Hello!

I just installed [filetype.nvim](https://github.com/nathom/filetype.nvim) to speed-up my nvim startup time but unfortunately it seems that committia will not open when writing a commit message.

Any idea/fix for this?

**Comment by nsfisis** [comment] 2021-12-04 16:56
I had the same trouble and found the cause.


Environment:

* Neovim: v0.6.0
* committia.vim: commit 0b4df1a7f48ffbc23b009bd14d58ee1be541917c
* [filetype.nvim](https://github.com/nathom/filetype.nvim): [commit ddef0fa](https://github.com/nathom/filetype.nvim/commit/ddef0faedfb561ca2af141a35ab6f256beba8b5a)
* Package manager: [paq-nvim](https://github.com/savq/paq-nvim) ([commit 94503ec](https://github.com/savq/paq-nvim/commit/94503ec7e719791fe2bda0fb0d6501c5a525f60f))


Cause:

`committia.vim` registers autocmd for `BufReadPost` event to setup itself.

```vim:plugin/committia.vim
" https://github.com/rhysd/committia.vim/blob/0b4df1a7f48ffbc23b009bd14d58ee1be541917c/plugin/committia.vim#L13
    autocmd BufReadPost COMMIT_EDITMSG,MERGE_MSG if s:should_open('gitcommit') | call committia#open('git') | endif
```

`s:should_open()` checks whether the current `filetype` option is equal to `gitcommit` or not.

`filetype.nvim` also registers autocmd for `BufRead` event to set filetype.

```vim:plugin/filetype.vim
" https://github.com/nathom/filetype.nvim/blob/ddef0faedfb561ca2af141a35ab6f256beba8b5a/plugin/filetype.vim#L3
    au BufNewFile,BufRead * lua require('filetype').resolve()
```

Because the autocmd event `BufRead` is just an alias for `BufReadPost`, these two event callbacks are fired in the order where they are registered, i.e., the order where the plugins are loaded. The loading order is, maybe, alphabetical or unspecified. Anyway, committia.vim can be loaded before filetype.nvim. In this case, `s:should_open()` returns false because `filetype` has not been determined yet.


Solution:

[This PR of filetype.nvim](https://github.com/nathom/filetype.nvim/pull/54) resolves the problem. It works for me.

**Comment by rhysd** [comment] 2021-12-04 17:49
@nsfisis Thank you for taking a look at this. It's really helpful. Let's wait for https://github.com/nathom/filetype.nvim/pull/54 being merged.

> The loading order is, maybe, alphabetical or unspecified.

When plugins are installed in different directories, the order is the same as the order of directories in `runtimepath`. If they're in the same, the order is implementation-defined. But it actually seems an alphabetical order.

**Comment by syphar** [comment] 2022-01-22 06:35
https://github.com/nathom/filetype.nvim/pull/54 was merged, and now this plugin works again for me.

**Closed** 2022-08-07 20:25 UTC
